In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/cgpa-vs-package-in-lpa/placement.csv


In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 


In [3]:
dataset = pd.read_csv("/kaggle/input/cgpa-vs-package-in-lpa/placement.csv")
dataset

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [4]:
new_data = dataset.head(10)
new_data

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57
5  7.89     2.99
6  6.73     2.60
7  6.75     2.48
8  6.09     2.31
9  8.31     3.51

In [5]:
x = dataset.iloc[:,:-1]
y = dataset["package"]


In [6]:
from sklearn.model_selection import LeaveOneOut, LeavePOut, KFold,StratifiedKFold

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
from sklearn.model_selection import cross_val_score

In [9]:
p = cross_val_score(LinearRegression(),x,y,cv= KFold(n_splits=10))

In [10]:
p.sort()
p

array([0.60480008, 0.65675401, 0.67205239, 0.69890411, 0.73505991,
       0.74376167, 0.80318103, 0.82098636, 0.82647996, 0.83963336])

In [11]:
x_new = new_data.iloc[:,:-1]
y_new = new_data["package"]
 

In [12]:
from sklearn.model_selection import LeaveOneOut, LeavePOut, KFold,StratifiedKFold

In [13]:
lo = KFold(n_splits =5)

for train,test in lo.split(x_new,y_new):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]
